name:                wallet-proxy
version:             0.41.3-0
github:              "Concordium/concordium-wallet-proxy"
author:              "Concordium"
maintainer:          "developers@concordium.com"
copyright:           "Concordium"
license-file:        "LICENSE"
license:             "Apache-2.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Concordium/concordium-wallet-proxy#readme>

dependencies:
- aeson >= 1.4.2
- async
- attoparsec-aeson
- base >=4.7 && < 5
- base16-bytestring >= 0.1.1.6
- bytestring >= 0.10
- cereal >= 0.5.7
- concordium-base
- concordium-client
- conduit == 1.3.*
- conduit-extra == 1.3.*
- containers >= 0.6
- cookie >= 0.4.5
- esqueleto
- http-client
- http-client-tls
- http-types >= 0.12
- http2-grpc-types >= 0.5
- microlens-platform
- monad-logger >= 0.3.30
- network-uri
- persistent >= 2.9.2
- persistent-postgresql >= 2.9
- random >= 1.1
- range >= 0.3
- text >= 1.2.3
- time
- yesod >= 1.6

default-extensions:
- RecordWildCards
- LambdaCase
- TupleSections
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- TypeOperators

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Werror=missing-fields
    - -Werror=missing-methods
    - -Wredundant-constraints
    - -fno-ignore-asserts

executables:
  wallet-proxy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -dynamic
    dependencies:
    - mtl
    - optparse-applicative
    - wallet-proxy
    - warp

tests:
  wallet-proxy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wallet-proxy
