name:                wallet-proxy
version:             0.28.0
github:              "Concordium/concordium-wallet-proxy"
author:              "Concordium"
maintainer:          "developers@concordium.com"
copyright:           "Concordium"
license-file:        "LICENSE"
license:             "Apache-2.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Concordium/concordium-wallet-proxy#readme>

dependencies:
- base >=4.7 && < 5
- bytestring >= 0.10
- case-insensitive >= 1.2.1.0
- concordium-base
- cookie >= 0.4.5
- cereal >= 0.5.7
- unordered-containers >= 0.2.9
- containers >= 0.6
- mtl >= 2.2.2
- aeson >= 1.4.2
- text >= 1.2.3
- base16-bytestring >= 0.1.1.6
- recursion-schemes >= 5.1
- vector >= 0.12
- split
- directory >= 1.3
- either
- filepath >= 1.4
- random >= 1.1
- persistent-template >= 2.7
- persistent-postgresql >= 2.9
- persistent >= 2.9.2
- microlens-platform
- monad-logger >= 0.3.30
- resource-pool >= 0.2.3.2
- conduit == 1.3.*
- conduit-extra == 1.3.*
- esqueleto
- http-types >= 0.12
- http2-grpc-types >= 0.5
- yesod >= 1.6
- warp >= 3.2
- time
- range >= 0.3
- concordium-client

default-extensions:
- RecordWildCards
- LambdaCase
- TupleSections
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Werror=missing-fields
    - -Werror=missing-methods
    - -Wredundant-constraints
    - -fno-ignore-asserts

executables:
  wallet-proxy:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -dynamic
    dependencies:
    - wallet-proxy
    - optparse-applicative

tests:
  wallet-proxy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wallet-proxy
